version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: inventory_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=inventory_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - inventory_network

networks:
  inventory_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
